name:                existential-optics
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/marcosh/existential-optics#readme
license:             OtherLicense
author:              Marco Perone
maintainer:          marco.perone@tweag.io
copyright:           2022 Tweag
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:       src
